apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.envName }}-{{ .Values.repoName }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: api-layer
